application: next-word
version: 2
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css

- url: /font
  static_dir: font

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: .*
  script: index.py

